/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}", "./public/index.html"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#55526c",
        "surface-variant": "#252242",
        "surface-container-lowest": "#000000",
        "secondary-dim": "#ff51fa",
        "error-container": "#a70138",
        "surface-container-high": "#1e1c39",
        "on-secondary-container": "#fff5f9",
        "on-secondary-fixed": "#620061",
        "tertiary-fixed": "#b8a3ff",
        background: "#0d0b21",
        tertiary: "#a68cff",
        primary: "#c1fffe",
        "on-primary-fixed": "#004343",
        "on-primary-container": "#005d5d",
        "primary-fixed-dim": "#00e6e6",
        "outline-variant": "#48455e",
        "on-error": "#490013",
        "on-tertiary-container": "#ffffff",
        "surface-container-low": "#121029",
        "surface-bright": "#2b284a",
        outline: "#76728e",
        "tertiary-container": "#7c4dff",
        "on-primary": "#006767",
        "tertiary-fixed-dim": "#ab93ff",
        "on-surface": "#e7e2ff",
        "tertiary-dim": "#7e51ff",
        "error-dim": "#d73357",
        "on-tertiary-fixed": "#1c0055",
        "primary-fixed": "#00f5f5",
        "surface-container-highest": "#252242",
        "on-background": "#e7e2ff",
        "on-primary-fixed-variant": "#006262",
        "primary-container": "#00ffff",
        "secondary-fixed-dim": "#ffa6f3",
        "surface-dim": "#0d0b21",
        surface: "#0d0b21",
        "on-tertiary": "#25006b",
        "on-secondary-fixed-variant": "#920091",
        "inverse-primary": "#006a6a",
        "inverse-surface": "#fcf8ff",
        secondary: "#ff51fa",
        "secondary-fixed": "#ffbdf3",
        "on-error-container": "#ffb2b9",
        "on-tertiary-fixed-variant": "#4000ad",
        error: "#ff6e84",
        "primary-dim": "#00e6e6",
        "on-surface-variant": "#aca8c5",
        "surface-container": "#191631",
        "surface-tint": "#c1fffe",
        "on-secondary": "#400040",
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
